-- =====================================================================
-- TERROIR TRAIL: Automated Supabase Seed Data
-- Populates 27 audited Crete producers/projects.
-- Unknown values remain NULL.
-- Experiences are intentionally NOT seeded before explicit producer approval.
-- =====================================================================

-- ---------------------------------------------------------------------
-- PRODUCERS SEED
-- ---------------------------------------------------------------------
INSERT INTO public.producers (
  id, name, greek_name, category, destination, country, country_code, region, village, lat, lng,
  cover_image, gallery, tag_line, description, story, indigenous_varieties,
  tasting_highlights, opening_hours, best_season, phone, website,
  google_maps_url,
  road_access, road_access_status, road_access_source_url, road_access_notes,
  location_status, location_source_url, location_notes,
  visit_status, visit_source_url, visit_notes,
  ethos, food_option, dog_friendly, kid_friendly, walk_in_friendly,
  campervan_friendly, price_level, rating, review_count, vip_perks
) VALUES
(
  'anoskeli-estate',
  'Anoskeli Winery & Olive Mill',
  'Οινοποιείο & Ελαιοτριβείο Ανώσκελη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Anoskeli (Platanias)',
  35.4598333333,
  23.7757861111,
  'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Mamidakis family roots, olive oil and wine in one village estate',
  'In the small Chania village that gave the brand its name, Anoskeli brings together olive groves, vineyards, a working olive mill, bottling facilities and a boutique winery. Olive oil, wine and tsikoudia all grow out of the same family connection to this corner of western Crete.',
  'The Mamidakis family traces its roots in Anoskeli to Alexandros and Irene Mamidakis. During difficult wartime years Irene cared for seven children and cultivated the family land; decades later the family invested back in the village, founding Anoskeli S.A. in 1983 and opening the modern olive mill in 1985.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Apr-20 Nov: Mon-Fri 10:00-18:00; booking strongly recommended; drop-ins subject to availability',
  NULL,
  '+30 28240 83126',
  'https://anoskeli.gr',
  'https://maps.google.com/?q=35.459833,23.775786',
  NULL,
  'not_publicly_confirmed',
  'https://anoskeli.gr',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://anoskeli.gr/en/',
  'Estate location in Anoskeli is verified by the producer; reservation number stored for visitor contact.',
  'seasonal_public',
  'https://anoskeli.gr/experiences',
  'The estate explicitly welcomes visitors for tastings and tours. Advance booking is strongly recommended; drop-ins are accepted subject to availability. Visitor season is published as April to 20 November.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'biolea-estate',
  'Biolea Astrikas Estate',
  'Βιολέα - Βιολογικό Ελαιοτριβείο',
  'olive_mill',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Astrikas (Kolymbari)',
  35.463807,
  23.743427,
  'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Fifth- and sixth-generation olive growers keeping stone milling alive in Astrikas',
  'Biolea is a family-owned single-estate olive-oil producer in Astrikas, where organic olives are stone-milled and cold-pressed using a modernized version of the traditional process. Its oils are grown, produced and bottled by the estate.',
  'Founder Yiorgos Dimitriadis spent decades researching how traditional olive-oil production could work in a modern estate. Today the fifth and sixth generations remain hands-on: Chloe Dimitriadis directs the harvest and mill, while she and her husband Michalis Papadakis continue the family business around olive oil, food and the Astrikas estate.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Tours by appointment Mon-Sun 10:00-17:00; Restaurant/Kafeneion Tue-Sun 11:00-15:30',
  NULL,
  '+30 28240 23281',
  'https://biolea.gr',
  'https://maps.google.com/?q=35.463807,23.743427',
  NULL,
  'not_publicly_confirmed',
  'https://biolea.gr/contact/',
  'Official Biolea contact information publishes the Astrikas Estate address and exact GPS point. No explicit road-surface, width, or vehicle-suitability classification is published, so road type remains unconfirmed.',
  'verified_entrance',
  'https://biolea.gr',
  'Exact GPS coordinates published by Biolea match the database pin.',
  'public_visits',
  'https://biolea.gr/',
  'Biolea explicitly welcomes visitors to the Astrikas estate. Guided olive-oil tours are by appointment; the estate also operates its restaurant and Kafeneion on published hours. Producer-operated tours and dining are direct Biolea offerings, not TerroirTrail Experiences.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'cretan-brewery-charma',
  'Cretan Brewery (Charma Beer)',
  'Κρητική Ζυθοποιία (Μπίρα Χάρμα)',
  'brewery',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Zounaki (Platanias)',
  35.48687,
  23.82586,
  'https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&w=1000&q=80', 'https://images.unsplash.com/photo-1538488881522-4326c36397ce?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Fresh Charma beer born from a Chania engineer''s idea',
  'Cretan Brewery sits among olive, avocado and orange groves in Zounaki and produces fresh Charma beer in Chania. It was the first brewery in the prefecture and grew around the idea that locally brewed, unpasteurised beer should be part of contemporary Cretan food culture.',
  'Mechanical engineer Ioannis Lionakis, born and raised in Chania, founded the brewery in 2007. His starting point was simple: he felt locals and visitors were missing the kind of fresh beer he had encountered elsewhere in Europe, so he set out to make it in western Crete.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  '8 Apr-31 Oct: daily 11:00-20:00; no brewery tours Sundays/bank holidays',
  NULL,
  '+30 28240 31002',
  'https://cretanbeer.gr',
  'https://maps.google.com/?q=35.486870,23.825860',
  NULL,
  'not_publicly_confirmed',
  'https://www.cretanbeer.gr/en/cretan-brewery/visit-us/',
  'Official visit information explicitly lists driving a car as a way to reach the brewery. It does not publish a road-surface, width, or vehicle-suitability classification, so no road type is published.',
  'verified_location',
  'https://www.cretanbeer.gr/en/contact/',
  'Current producer address verified as Zounaki, Platanias. Site coordinate retained as verified brewery location; entrance/access grading remains separate.',
  'seasonal_public',
  'https://www.cretanbeer.gr/en/cretan-brewery/visit-us/',
  'Cretan Brewery publishes a visitor season from 8 April to 31 October, daily 11:00-20:00. Guided brewery tours are not offered Sundays or bank holidays.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'karavitakis-winery',
  'Karavitakis Winery',
  'Οινοποιείο Καραβιτάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Pontikiana (Kolymbari)',
  35.5019916667,
  23.7911722222,
  'https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Eighty years of family winemaking in the hills of Chania',
  'Karavitakis is a family winery in Pontikiana, surrounded by the hills, vineyards and olive groves of the Kolymbari area. Its wines draw on both local Cretan grapes and selected international varieties from estate and contracted vineyards.',
  'The family describes an eighty-year winemaking legacy in western Crete. Rather than turning that history into a museum piece, the current generation has built a boutique winery with modern equipment and continues experimenting with different varieties and carefully selected vineyard sites.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Visitors accepted with or without appointment; check current tour availability',
  NULL,
  '+30 28240 23381',
  'https://karavitakiswines.com',
  'https://maps.google.com/?q=35.501992,23.791172',
  NULL,
  'not_publicly_confirmed',
  'https://karavitakiswines.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://www.karavitakiswines.com/',
  'Pontikiana winery location and contact details are producer-verified; coordinates match Wines of Crete route data.',
  'public_visits',
  'https://www.karavitakiswines.com/',
  'Karavitakis explicitly welcomes visitors with or without appointments; appointments remain preferable for a guided visit.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"freeMeze":"Chania Kalamata olives & sourdough","welcomePour":"Kompsos Sparkling Romaiko","discountPercent":10}'::JSONB
),
(
  'lafkas-brewery',
  'Lafkas Brewery',
  'Ζυθοποιία Λάφκας',
  'brewery',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Pazinos',
  35.494636,
  23.986088,
  'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Greek–Belgian brewing roots, handcrafted in Chania',
  'Lafkas Brewery is the Chania brewery of Michalis Lafkas and Aurelie Petillion. Their beers combine Michalis''s studies in winemaking and beverage technology with Aurelie''s Belgian beer background in a small-scale, unfiltered and unpasteurised brewing project.',
  'The story began in 2011, when Michalis was studying winemaking and beverage technology and travelled to Belgium, where he met Aurelie. Five years later they were living together in Crete and developing their own Greek–Belgian beer; in 2017 they launched their first release, a Triple Hop Pale Ale.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'By appointment',
  NULL,
  '+30 6945430402',
  'https://lafkasbrewery.com',
  'https://www.google.com/maps/place/Lafkas+Brewery/@35.494636,23.9835131,17z/data=!3m1!4b1!4m6!3m5!1s0x149c8788ddc82b49:0x8ee32eaeecced606!8m2!3d35.494636!4d23.986088!16s%2Fg%2F11fxb2y0bz?entry=tts&g_ep=EgoyMDI0MDUwNi4wKgBIAVAD',
  NULL,
  'not_publicly_confirmed',
  'https://lafkasbrewery.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://www.google.com/maps/place/Lafkas+Brewery/@35.494636,23.9835131,17z/data=!3m1!4b1!4m6!3m5!1s0x149c8788ddc82b49:0x8ee32eaeecced606!8m2!3d35.494636!4d23.986088!16s%2Fg%2F11fxb2y0bz?entry=tts&g_ep=EgoyMDI0MDUwNi4wKgBIAVAD',
  'Current Lafkas Brewery Google Maps business pin supplied by the TerroirTrail project owner and corroborated by the official Pazinos address. Location verified; entrance-level precision has not been separately established.',
  'appointment_only',
  'https://lafkasbrewery.com/',
  'Lafkas explicitly states that the Pazinos brewery is open by appointment. This is visitability only; no TerroirTrail bookable experience exists.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'manousakis-winery',
  'Manousakis Winery',
  'Οινοποιείο Μανουσάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Vatolakkos',
  35.4490416667,
  23.8878194444,
  'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'A homecoming to Vatolakkos, bottled under the name Nostos',
  'Manousakis Winery is a family estate in Vatolakkos, in the foothills of the White Mountains, producing wines under the Nostos name. The winery''s identity is tied as much to return and family memory as to vineyards and cellar work.',
  'Ted Manousakis was born in Vatolakkos in 1943 and left Crete for the United States at the age of eleven. His desire to reconnect with the village eventually became the winery: the first vineyards were planted in 1993, and the wines took the name Nostos, the Greek idea of yearning to return home. His daughter Alexandra made a similar return in 2007, leaving New York for Crete and helping grow the family winery.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  '1 Jun-18 Oct 2026: Mon-Sat 12:00-22:00; Sun closed; booking required',
  NULL,
  '+30 28210 78787',
  'https://manousakiswinery.com',
  'https://maps.google.com/?q=35.449042,23.887819',
  NULL,
  'not_publicly_confirmed',
  'https://www.manousakiswinery.com/contact',
  'Official contact information provides Getting Here options by car, taxi, bus and shuttle. It does not publish a road-surface, width, or vehicle-suitability classification, so no road type is published.',
  'verified_location',
  'https://www.manousakiswinery.com/contact',
  'Vatolakkos winery location and coordinates are verified through producer and Wines of Crete sources.',
  'appointment_only',
  'https://www.manousakiswinery.com/visit',
  'Manousakis publishes seasonal visitor hours and requires bookings for visits.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'monumental-olive-tree-vouves',
  'Olive Tree Museum of Vouves & Monumental Olive Tree',
  'Μουσείο Ελιάς Βουβών & Μνημειακή Ελιά',
  'olive_mill',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Ano Vouves',
  35.48703,
  23.78679,
  'https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Olive heritage gathered around one of Crete''s living monuments',
  'In Ano Vouves, the protected Monumental Olive Tree and the neighbouring Olive Tree Museum preserve the agricultural memory of western Crete. The museum occupies a traditional village building and presents tools connected with olive cultivation, harvesting, transport and olive-oil production.',
  'The Monumental Olive Tree was declared a protected natural monument in 1997. Beside it, the Olive Tree Museum opened in 2009 in a traditional building dating to around 1800, preserving the tools and everyday objects of the region''s olive-growing culture. The site should be understood as rural heritage rather than as an olive-oil producer or commercial estate.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Apr-Oct: daily 10:00-19:00; Nov-Mar by agreement',
  NULL,
  '+30 28240 22279',
  NULL,
  'https://maps.google.com/?q=35.48703,23.78679',
  NULL,
  'not_publicly_confirmed',
  NULL,
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://visitchania.gr/en/places-to-visit/museum-of-olive-vouves/',
  'This is a heritage attraction/local project rather than a producer. Coordinates identify the museum/tree site, not a commercial olive mill.',
  'seasonal_public',
  'https://www.cretetravel.com/en/activity/82/Olive_Tree_Museum_of_Vouves',
  'The museum and monumental tree are publicly visitable April-October; winter access is by prior agreement.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'stathakis-honey-park',
  'StathakisFamily Cretan Honey Experience',
  'Μελισσοκομία Σταθάκη - Πάρκο Μέλισσας',
  'apiary',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Kaloudiana (Kissamos)',
  35.480012,
  23.689595,
  'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'More than sixty years of family beekeeping from Kissamos',
  'StathakisFamily is a Kissamos honey producer whose work spans beekeeping, honey packing and a seasonal visitor site in Kaloudiana. The family produces several Cretan honey types alongside other bee products.',
  'The family business began in 1963 when Stelios Stathakis acquired his first hives. More than sixty years later, the next generations have expanded the operation with a modern packing facility while keeping beekeeping—not tourism—as the foundation of the family business.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Spring-Summer; check current visitor hours before travelling',
  NULL,
  '+30 6977906195',
  'https://stathakisfamily.com',
  'https://maps.google.com/?q=35.480012,23.689595',
  NULL,
  'not_publicly_confirmed',
  'https://stathakisfamily.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_entrance',
  'https://stathakisfamily.com',
  'Exact visitor-site coordinates verified from the producer-controlled map link.',
  'seasonal_public',
  'https://stathakisfamily.com/about-us/',
  'The family explicitly lists its Cretan Honey Experience site in Kaloudiana as open during spring and summer. This does not make its paid activities TerroirTrail experiences.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"freeMeze":"Fresh sheep yogurt with pollen granules","welcomePour":"Wild Malotira herbal tea with pure comb honey","discountPercent":10}'::JSONB
),
(
  'wild-herbs-kallikratis',
  'Wild Herbs of Crete',
  'Άγρια Βότανα Κρήτης - Καλλικράτης',
  'apiary',
  'crete',
  'Greece',
  'GR',
  'Chania',
  'Kallikratis (Sfakia)',
  35.2378367,
  24.2565003,
  'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Janina and Babis among the wild aromatic plants of Sfakia',
  'Wild Herbs of Crete grew from Janina and Babis Psaroudakis''s work collecting and distilling aromatic plants around Kallikratis and the mountains of Sfakia. Their archive documents herbs, essential oils, hydrolates, soaps and the practical knowledge of working with plants in a rugged landscape.',
  'Their old field notes make the work tangible: collecting wild dittany meant climbing carefully on rocky slopes and taking only leaves so the perennial roots remained alive. In 2011 they also documented opening a tiny mountain café in Kallikratis where herbs, soaps and essential oils sat alongside coffee and homemade lemonade.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Wed-Sun 11:00-19:00 (seasonal; check current listing before travel)',
  NULL,
  '+30 6949092073',
  'https://wildherbsofcrete.com',
  'https://www.google.com/maps/place/Wild+Herbs+of+Crete/@35.2376928,24.2562818,21z/data=!4m22!1m15!4m14!1m6!1m2!1s0x149b64897e85fdbf:0x23fbfa93da44674!2zV2lsZCBIZXJicyBvZiBDcmV0ZSwgzprOsc67zrvOuc66z4HOrM-EzrfPgiA3MzAgMTE!2m2!1d24.2565003!2d35.2378367!1m6!1m2!1s0x149a586bd068e13f:0x400bd2ce2b9b6f0!2zzpfPgc6szrrOu861zrnOvw!2m2!1d25.1421291!2d35.3386746!3m5!1s0x149b64897e85fdbf:0x23fbfa93da44674!8m2!3d35.2378367!4d24.2565003!16s%2Fg%2F1q5glqyf8?entry=ttu&g_ep=EgoyMDI2MDkwOS4wIKXMDSoASAFQAw%3D%3D',
  NULL,
  'current_access_uncertain',
  'https://cretazine.com/en/crete/travel-explore/crete-360/item/1269-herbal-sanctuaries-of-crete',
  'Current first-party road-surface and vehicle-suitability guidance was not found. An older independent report describes dusty mountain roads to Kallikratis and says the Fragkokastelo approach is more difficult. Because that evidence is old and route-dependent, no current road classification is published; confirm conditions before driving.',
  'verified_location',
  'https://www.google.com/maps/place/Wild+Herbs+of+Crete/@35.2376928,24.2562818,21z/data=!4m22!1m15!4m14!1m6!1m2!1s0x149b64897e85fdbf:0x23fbfa93da44674!2zV2lsZCBIZXJicyBvZiBDcmV0ZSwgzprOsc67zrvOuc66z4HOrM-EzrfPgiA3MzAgMTE!2m2!1d24.2565003!2d35.2378367!1m6!1m2!1s0x149a586bd068e13f:0x400bd2ce2b9b6f0!2zzpfPgc6szrrOu861zrnOvw!2m2!1d25.1421291!2d35.3386746!3m5!1s0x149b64897e85fdbf:0x23fbfa93da44674!8m2!3d35.2378367!4d24.2565003!16s%2Fg%2F1q5glqyf8?entry=ttu&g_ep=EgoyMDI2MDkwOS4wIKXMDSoASAFQAw%3D%3D',
  'Current Wild Herbs of Crete Google Maps business pin in Kallikratis supplied by the TerroirTrail project owner. Location verified; entrance-level precision has not been separately established.',
  'seasonal_public',
  'https://www.google.com/maps/place/Wild+Herbs+of+Crete/@35.2376928,24.2562818,21z/data=!4m22!1m15!4m14!1m6!1m2!1s0x149b64897e85fdbf:0x23fbfa93da44674!2zV2lsZCBIZXJicyBvZiBDcmV0ZSwgzprOsc67zrvOuc66z4HOrM-EzrfPgiA3MzAgMTE!2m2!1d24.2565003!2d35.2378367!1m6!1m2!1s0x149a586bd068e13f:0x400bd2ce2b9b6f0!2zzpfPgc6szrrOu861zrnOvw!2m2!1d25.1421291!2d35.3386746!3m5!1s0x149b64897e85fdbf:0x23fbfa93da44674!8m2!3d35.2378367!4d24.2565003!16s%2Fg%2F1q5glqyf8?entry=ttu&g_ep=EgoyMDI2MDkwOS4wIKXMDSoASAFQAw%3D%3D',
  'Current public business listing shows Wild Herbs of Crete open seasonally in Kallikratis, with published hours Wednesday-Sunday. Hours can change seasonally, so travelers should check the current listing or call before making a long mountain drive.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'aerakis-dairy-anogeia',
  'Aerakis Cheese Products',
  'Παραδοσιακό Τυροκομείο Αεράκη',
  'cheese_dairy',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Sokaras (Gortyna)',
  35.065803,
  25.106932,
  'https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Family cheesemaking rooted in Sokaras and the Asterousia landscape',
  'A family dairy in Sokaras, Gortyna, making traditional Cretan cheeses from sheep and goat milk collected around the Asterousia area. The business pairs local raw material and inherited cheesemaking knowledge with modern traceability and food-safety systems.',
  'Aerakis is a family-owned dairy in Sokaras with a long-standing tradition in Cretan cheesemaking. Its production uses sheep and goat milk collected from local farmers in the Asterousia region, combining traditional cheesemaking methods with modern food-safety, traceability and quality-control systems.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Contact producer before visiting',
  NULL,
  '+30 28930 31990',
  'https://cretancheeseaerakis.com',
  'https://www.google.com/maps?ll=35.065803,25.106932&z=15&t=m&hl=en-US&gl=US&mapclient=embed&cid=8450329635840177008',
  NULL,
  'not_publicly_confirmed',
  'https://cretancheeseaerakis.com/',
  'Official Aerakis information confirms the dairy is based in Sokaras, Gortyna. No explicit public road-surface, width, or vehicle-suitability guidance was found, so road type remains unconfirmed.',
  'verified_location',
  'https://www.google.com/maps?ll=35.065803,25.106932&z=15&t=m&hl=en-US&gl=US&mapclient=embed&cid=8450329635840177008',
  'Current Aerakis Cheese Products location supplied from the Google Maps business listing. Treat as verified location; entrance-level precision has not been separately established.',
  'not_publicly_confirmed',
  'https://cretancheeseaerakis.com/',
  'The producer verifies the working dairy in Sokaras but does not currently publish visitor instructions on its own site. Do not present the dairy as a walk-in attraction.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"freeMeze":"Slice of 2-year cave-aged Graviera","welcomePour":"Fresh alpine sheep whey warm drink","discountPercent":10}'::JSONB
),
(
  'domaine-paterianakis',
  'Domaine Paterianakis',
  'Κτήμα Πατεριανάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Melesses (Peza)',
  35.1808944444,
  25.1963472222,
  'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Organic Peza wines shaped by one family across generations',
  'Domaine Paterianakis is a family estate in Melesses, inside the Peza wine region, with vineyards cultivated organically and biodynamically around a gravity-designed winery. Cretan varieties remain at the centre of its identity.',
  'The family vineyard predates the modern estate: Aristides Nikoloudakis established vines here, and Manolis Paterianakis moved toward organic cultivation in 1980. Giorgos Paterianakis created the present estate in 1988 and produced its first organic wine in 1997; today his daughters Emmanuela and Niki continue the work in wine production and sales.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Apr-mid Nov: Mon-Fri 10:30-17:30, Sat-Sun 10:30-16:00; mid-Nov-Mar by appointment',
  NULL,
  '+30 2810 226674',
  'https://paterianakis.gr',
  'https://maps.google.com/?q=35.180894,25.196347',
  NULL,
  'not_publicly_confirmed',
  'https://paterianakis.gr',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://paterianakis.gr/en/',
  'Winery coordinates match Wines of Crete route data and the current producer location in Melesses.',
  'seasonal_public',
  'https://paterianakis.gr/en/events/',
  'The estate welcomes visitors April to mid-November on published hours; from mid-November through March visits are by appointment.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'douloufakis-winery',
  'Douloufakis Winery',
  'Οινοποιείο Δουλουφάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Dafnes',
  35.215109,
  25.049664,
  'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80', 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Three generations in Dafnes, with Vidiano at the centre',
  'Douloufakis Winery is rooted in the village of Dafnes and works with both indigenous Cretan grapes and selected international varieties. Its modern cellar grew from a family wine business that began well before bottled estate wine became common on Crete.',
  'Dimitris Douloufakis began professional winemaking in 1930, his son George took over in 1960, and grandson Nikos returned from oenology studies in Alba, Italy, to lead the winery in 1993. In 2000 Nikos turned his attention to the then little-known Vidiano grape and began planting and vinifying it seriously.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Mon-Fri cellar 10:00-15:30; tours/tastings by advance booking; seasonal Saturday tastings Jun-Sep',
  NULL,
  '+30 2810 792017',
  'https://douloufakis.wine',
  'https://maps.google.com/?q=35.215109,25.049664',
  NULL,
  'not_publicly_confirmed',
  'https://douloufakis.wine/en/getting-here/',
  'Official directions confirm access by car from Heraklion via the Heraklion–Moires highway, Stavrakia–Siva provincial road and final village streets, with winery parking. The official page does not explicitly classify road surface, width, or rental-car suitability, so no road type is published.',
  'verified_location',
  'https://douloufakis.wine/en/contact-us/',
  'Winery coordinates and Dafnes location are verified through producer and Wines of Crete sources.',
  'appointment_only',
  'https://douloufakis.wine/en/',
  'The winery offers visits and tastings, but advance booking is required for visitor programs. Public production-site existence does not imply walk-in access.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'gavalas-crete-winery',
  'Fragospito Winery (Domaine Gavalas)',
  'Οινοποιείο Φραγκόσπιτο - Κτήμα Γαβαλά',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Vorias (Monofatsi)',
  35.09995,
  25.1172527778,
  'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Organic vineyards in Vorias with a story reaching back to 1906',
  'Fragospito, the Gavalas family winery of Vorias Monofatsi, grows Cretan and international varieties in organically cultivated vineyards. The current winery stands inside the vineyards and handles the process from grapes through bottling.',
  'The family story starts in 1906, when Emmanuel Gavalas planted vineyards and used an old dressed-stone grape treading tank at Agios Thomas before settling in Vorias. Later generations continued the vineyards; they entered organic cultivation in 2001 and the family built the modern winery among them in 2004.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Contact winery before visiting',
  NULL,
  '+30 28940 51060',
  'https://www.fragospitowinery.com/en/',
  'https://maps.google.com/?q=35.099950,25.117253',
  NULL,
  'not_publicly_confirmed',
  'https://www.fragospitowinery.com/en/',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://www.fragospitowinery.com/en/',
  'Crete winery identity and Vorias location verified. The former gavalaswines.gr link belonged to the unrelated Santorini Gavalas winery and has been replaced.',
  'current_access_uncertain',
  'https://www.fragospitowinery.com/visit/',
  'Fragospito publishes a guided-tour/tasting page, but the site does not provide a clearly current visitor timetable. Contact the winery before travelling.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'kasta-brewery',
  'KASTA Microbrews',
  'Μικροζυθοποιία Κάστα',
  'brewery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Heraklion City Center',
  35.338429,
  25.131678,
  'https://images.unsplash.com/photo-1538488881522-4326c36397ce?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1538488881522-4326c36397ce?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'A biologist, a pharmacist and a family brewing lab',
  'KASTA Microbrews is a small family brewery in central Heraklion producing fresh, unfiltered and unpasteurised beer in small batches. Its compact brewing lab is intentionally close to the city rather than hidden in an industrial estate.',
  'Biologist and brewer Kostas Antonakakis founded KASTA with his wife Anna Tzani, a pharmacist, opening the Heraklion brewing lab in late 2018. Even the name is personal: KASTA is an acronym built from the initials of members of their family.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Mon-Fri 09:00-17:00',
  NULL,
  '+30 2811 813479',
  'https://kastabeer.com',
  'https://maps.google.com/?q=35.338429,25.131678',
  NULL,
  'not_publicly_confirmed',
  'https://kastabeer.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://kastabeer.com',
  'Current brewery address verified as Zampeliou 6, Heraklion.',
  'public_visits',
  'https://kastabeer.com/about-us/',
  'KASTA publishes showroom visiting hours at its Heraklion Brewing Lab. A tasting session is a separate producer offering and is not a TerroirTrail experience.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'lyrarakis-winery',
  'Lyrarakis Winery',
  'Οινοποιείο Λυραράκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Alagni',
  35.1848888889,
  25.2082222222,
  'https://images.unsplash.com/photo-1474722883778-792e7990302f?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1474722883778-792e7990302f?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'The family that helped bring rare Cretan grapes back',
  'Lyrarakis is a family winery established in 1966 and closely associated with the revival of indigenous Cretan grape varieties. The winery works across distinctive island terroirs while keeping rare local grapes at the heart of its range.',
  'Brothers Manolis and Sotiris Lyrarakis founded the winery in 1966. The family planted the rare Dafni and Plyto varieties in the Psarades vineyard in 1992 and later gave Melissaki a home at Gero Deti in 2010—part of a continuing search for Cretan grapes that had almost disappeared.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Apr-Oct: daily 11:30-19:00, last tasting 17:30; Nov-Mar by request; bank holidays closed',
  NULL,
  '+30 6981050681',
  'https://lyrarakis.com',
  'https://maps.google.com/?q=35.184889,25.208222',
  NULL,
  'not_publicly_confirmed',
  'https://lyrarakis.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_entrance',
  'https://lyrarakis.com/en/visit-us',
  'Producer publishes exact tasting/event GPS coordinates: 35°11''05.6"N 25°12''29.6"E, matching the database pin.',
  'seasonal_public',
  'https://lyrarakis.com/en/visit-us',
  'The tasting site is open daily April-October on published hours; November-March visits are available on request.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'meligyris-apiary',
  'Meligyris',
  'Μελίγυρις Κρητικό Μέλι',
  'apiary',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Arkalochori',
  35.1499302,
  25.2656256,
  'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Family beekeeping since 1920, studied through a scientist''s lens',
  'Meligyris produces Cretan honeys from wild and cultivated landscapes around the island, with an emphasis on how place changes aroma, composition and character. The company is based in Arkalochori and builds on a family beekeeping tradition reaching back to 1920.',
  'Manolis Stefanakis grew up inside that beekeeping tradition and later studied at the Agricultural University of Athens. He brought the two worlds together by examining how altitude, humidity, soil and local microclimates affect the organoleptic and biochemical character of each honey.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Contact producer before visiting',
  NULL,
  '+30 28910 29066',
  'https://meligyris.com',
  'https://maps.google.com/?q=35.149930,25.265626',
  NULL,
  'not_publicly_confirmed',
  'https://meligyris.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_entrance',
  'https://meligyris.com',
  'Exact coordinates verified from the producer-controlled map destination.',
  'not_publicly_confirmed',
  'https://meligyris.com/pages/contact',
  'Meligyris publishes its Arkalochori production/contact address but does not currently advertise the site as a public visitor attraction on its own website.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'notos-brewery',
  'Notos Brewery',
  'Ζυθοποιία Νότος',
  'brewery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Kaminia (Heraklion)',
  35.3293991,
  25.1142006,
  'https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Four childhood friends who built Heraklion''s first microbrewery',
  'Notos is an independent brewery in Heraklion that grew out of home brewing, friendship and a desire to make local craft beer in a city that did not yet have its own microbrewery. It remains a distinctly urban Cretan beer project.',
  'Childhood friends Antonis Tampakakis, Giorgos Neroladakis, Kostas Verigos and Lambros Petsalakis spent years talking, planning and learning before turning their brewing hobby into Notos. Their project became Heraklion''s first microbrewery and introduced their own local craft beer to the city.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Contact brewery before visiting',
  NULL,
  '+30 2811 117167',
  'https://notosbrewery.gr',
  'https://maps.google.com/?q=35.329399,25.114201',
  NULL,
  'not_publicly_confirmed',
  'https://notosbrewery.gr',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://notosbrewery.gr',
  'Current address verified as Patriarchou Meletiou Metaxaki 36A, Heraklion.',
  'not_publicly_confirmed',
  'https://brewshop.notosbrewery.gr/?page_id=282',
  'Notos publishes its brewery address and direct brewer contact details, but its current official pages do not clearly advertise general public visiting hours.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'peskesi-farm-kazani',
  'Peskesi Organic Farm',
  'Αγρόκτημα Πεσκέσι',
  'kazani',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Charaso (Hersonissos)',
  35.2751612,
  25.2996351,
  'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Regenerative farming at the root of a wider Cretan food philosophy',
  'Peskesi''s farm in Charaso combines vegetable gardens, olive groves, herbs and livestock under certified organic, biodynamic and regenerative cultivation. It is the agricultural base behind a broader effort to keep Cretan ingredients connected to the land and seasons that produce them.',
  'The farm follows what Peskesi calls a “Farm to Table” and “Table to Farm” cycle: food begins in the soil, while organic material and knowledge return to the farm rather than ending at the plate. The result is less a showcase farm than a working attempt to make cultivation, cooking and waste reduction part of one system.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Farm: Mon-Fri 09:00-15:00; check activity/visit requirements before travelling',
  NULL,
  '+30 6988889994',
  'https://peskesicrete.gr',
  'https://maps.google.com/?q=35.275161,25.299635',
  'unpaved_passable',
  'verified',
  'https://peskesicrete.gr/en/experiences/explore-the-farm',
  'Producer states that access to the farm is via a passable dirt road; entry is limited to vehicles up to 20 seats. The producer recommends approaching through Skotino, Voritsi and Charaso from the Gouves area and following wooden signs. This verifies passable unpaved access but does not by itself establish rental-car suitability.',
  'verified_location',
  'https://peskesicrete.gr',
  'Current Peskesi farm location verified as Charaso, Hersonissos. Producer approval is still required for TerroirTrail experiences.',
  'public_visits',
  'https://peskesicrete.gr/en/experiences/explore-the-farm',
  'Peskesi publishes the Charaso farm as a visitor destination and gives access directions. Individual activities may require separate booking with Peskesi; none are TerroirTrail experiences.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"freeMeze":"Freshly baked sourdough with wood-fired anthotiro","welcomePour":"Single-Estate Wild Thyme Tsikoudia","discountPercent":10}'::JSONB
),
(
  'silva-daskalaki-winery',
  'Silva Daskalaki Winery',
  'Οινοποιείο Σίλβα Δασκαλάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Siva (Heraklion)',
  35.2088833333,
  25.0358527778,
  'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'A Siva family tradition carried into modern organic winemaking',
  'Silva Daskalaki is a family winery in Siva, Heraklion, working with organically cultivated vineyards and Cretan varieties within the wider Dafnes wine landscape. The current winery combines family continuity with modern cellar practice.',
  'The Daskalaki family dates its viticulture and winemaking tradition to 1920. In 1998 Irini Daskalaki-Xenogiannaki began building the modern winery in Siva; by 2004 the family had made its first official bottlings of dry and naturally sweet Liatiko.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Apr-Oct: Mon-Sat 10:30-17:30; Nov-Mar: Mon-Fri 10:30-17:30; appointment required one day ahead',
  NULL,
  '+30 2810 792021',
  'https://silvawines.gr',
  'https://maps.google.com/?q=35.208883,25.035853',
  NULL,
  'not_publicly_confirmed',
  'https://silvawines.gr',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://www.silvawines.gr/en/about-us',
  'Siva winery coordinates match Wines of Crete route data; producer contact details verified.',
  'appointment_only',
  'https://www.silvawines.gr/en/guided-tours-tasting-amp-wine-tips',
  'Silva Daskalaki requires arrangements one day in advance for winery visits and tastings.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"freeMeze":"Aged sheep Graviera & carob rusks","welcomePour":"Biodynamic Vorinos Vidiano","discountPercent":15}'::JSONB
),
(
  'solo-craft-brewery',
  'Solo Cretan Craft Brewery',
  'Μικροζυθοποιία Σόλο',
  'brewery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Kallithea (Heraklion)',
  35.3117,
  25.176,
  'https://images.unsplash.com/photo-1538488881522-4326c36397ce?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1538488881522-4326c36397ce?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Heraklion craft beer built around experimentation and human contact',
  'Solo is an independent Cretan craft brewery based in Heraklion, founded in late 2015. Its identity is intentionally experimental, moving across beer styles rather than treating craft brewing as a fixed set of labels.',
  'From the beginning, Solo framed good beer as something social rather than simply commercial—its own language says craft beer is about people, togetherness and sharing ideas. That philosophy explains why experimentation and dialogue with beer drinkers are part of the brewery''s identity.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Mon-Fri 11:00-16:00; Sat-Sun by appointment; contact before visiting',
  NULL,
  '+30 2811 750209',
  'https://solobeer.gr',
  'https://maps.google.com/?q=35.311700,25.176000',
  NULL,
  'not_publicly_confirmed',
  'https://solobeer.gr/en/',
  'Official Solo Brewery information publishes a How to Reach address and Google Map for the Kallithea brewery. No explicit road-surface, width, or vehicle-suitability classification is published, so road type remains unconfirmed.',
  'verified_location',
  'https://solobeer.gr',
  'Current production-site address verified as Kountourioti 35, Heraklion.',
  'appointment_only',
  'https://solobeer.gr/en/',
  'Solo welcomes visitors but explicitly asks them to contact the brewery in advance so the visit can be scheduled; weekends are by appointment.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'kazani-stilianou',
  'Stilianou Winery',
  'Οινοποιείο Στυλιανού',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Kounavoi',
  35.2358583333,
  25.1914,
  'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Five generations of natural and organic wine in Kounavoi',
  'Stilianou is a small family winery in the historic wine country around Kounavoi and Archanes, producing natural and organically grown wines with a strong emphasis on indigenous Cretan grapes. Olive oil is part of the same family agricultural landscape.',
  'The family dates its domain to 1922 and describes five generations of winemakers. The continuity is less about reproducing the past unchanged than keeping native varieties, vineyards and family-scale production at the centre while working in a contemporary natural-wine style.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Daily from 11:00; Nov-Mar by booking; check current closing time',
  NULL,
  '+30 6940784329',
  'https://stilianouwinery.com',
  'https://maps.google.com/?q=35.235858,25.191400',
  NULL,
  'not_publicly_confirmed',
  'https://stilianouwinery.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://stilianouwinery.com/',
  'Current winery identity, visitor operation and phone verified on the producer site. Closing time varies between current producer pages, so users should check the booking page.',
  'public_visits',
  'https://stilianouwinery.com/',
  'Stilianou publishes winery visiting/tasting hours; from November to March visits are by booking. Check the producer page for the current closing time.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'titakis-winery',
  'Titakis Winery',
  'Οινοποιείο Τιτάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Kounavi (Peza PDO)',
  35.2330555556,
  25.1838666667,
  'https://images.unsplash.com/photo-1574856344991-aaa31b6f4ce3?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1574856344991-aaa31b6f4ce3?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Three generations moving Cretan wine from Kalloni to Kounavoi',
  'Titakis is a three-generation Cretan winery whose modern production base is in Kounavoi. Its history follows the wider transition of island wine from small family production toward estate vineyards, bottling and contemporary cellar work.',
  'Titos Titakis founded the first family winery in Kalloni in 1952, and his son Nikolaos expanded its commercial reach. Production moved to modern facilities in Kounavoi in 1996; the third generation entered management in 2005 and has continued expanding the family''s vineyards and wine portfolio.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Book Fabrika visit with the winery; contact for current hours',
  NULL,
  '+30 2810 743630',
  'https://titakis.gr',
  'https://maps.google.com/?q=35.2330555556,25.1838666667',
  NULL,
  'not_publicly_confirmed',
  'https://titakis.gr',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://titakis.gr/en/history/',
  'Coordinates normalized to Wines of Crete Kounavoi location; current phone verified by the winery and Wines of Crete.',
  'appointment_only',
  'https://titakis.gr/en/contact/',
  'Titakis publishes the Fabrika visitor concept and a booking route for winery visits; do not imply walk-in availability without confirmation.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'zacharioudakis-winery',
  'Zacharioudakis Organic Winery',
  'Βιολογικό Οινοποιείο Ζαχαριουδάκη',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Heraklion',
  'Plouti (Messara Valley)',
  35.0773388889,
  24.9414527778,
  'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'A journalist''s return to family land on Orthi Petra',
  'Domaine Zacharioudakis is an organic wine estate on the steep Orthi Petra hill near Plouti, above the Messara landscape. The vineyard wraps around the hill on stone-supported slopes, with the winery built directly into the estate.',
  'Journalist Stelios Zacharioudakis and his wife Victoria began creating the estate in 2000 on land connected to his father and grandfather. By 2009 the project had grown into a completed winery, and Zacharioudakis describes that moment as the point when journalism moved to the background and winemaking became his daily work.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Apr-Oct: Mon-Sat 10:00-17:00; winter visits after contact',
  NULL,
  '+30 28920 96226',
  'https://zacharioudakis.com',
  'https://maps.google.com/?q=35.077339,24.941453',
  NULL,
  'not_publicly_confirmed',
  'https://zacharioudakis.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://www.winesofcrete.gr/en/wineries/domaine-zacharioudakis/',
  'Plouti estate coordinates and current visitor details are verified through Wines of Crete.',
  'seasonal_public',
  'https://www.winesofcrete.gr/en/wineries/domaine-zacharioudakis/',
  'The winery and vineyard are open to visitors April-October, Monday-Saturday 10:00-17:00. During winter, contact the estate before visiting.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"freeMeze":"Messara artisanal dried figs & cheese","welcomePour":"Orthi Petra Organic Vidiano","discountPercent":10}'::JSONB
),
(
  'parasiris-olive-mill',
  'Paraschakis Family Olive Oil Factory',
  'Ελαιοτριβείο Παρασχάκη',
  'olive_mill',
  'crete',
  'Greece',
  'GR',
  'Rethymno',
  'Melidoni (Mylopotamos)',
  35.37587,
  24.72841,
  'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Generations of olive-oil making in Melidoni',
  'The Paraschakis family olive mill in Melidoni is both a working family business and a place where older and modern methods of olive-oil production can be understood side by side. The family continues to make extra virgin olive oil in Mylopotamos.',
  'The mill has remained in the Paraschakis family for generations. Rather than discarding older equipment as production modernised, the family kept the story visible: visitors can see how pressing moved from manual and animal-powered methods to contemporary centrifugal extraction.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Mon-Sat 09:00-18:00; Sunday closed (check current listing before travel)',
  NULL,
  '+30 28340 22039',
  'https://paraschakis.gr',
  'https://maps.google.com/?q=35.375870,24.728410',
  NULL,
  'not_publicly_confirmed',
  'https://paraschakis.gr',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://paraschakis.gr/olive-oil-factory/',
  'Current official site verifies the Paraschakis family olive mill in Melidoni. The public landline +30 28340 22039 is consistently listed by the Municipality/local business sources and current travel listings.',
  'public_visits',
  'https://paraschakis.gr/olive-oil-factory/',
  'The Paraschakis family explicitly welcomes visitors to the Melidoni olive mill for an introduction to older and modern production methods and olive-oil tasting. Current public listings show Monday-Saturday 09:00-18:00; check before a special trip.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'tzourmpakis-dairy-amari',
  'Tzourmpakis Dairy',
  'Τυροκομείο Τζουρμπάκη',
  'cheese_dairy',
  'crete',
  'Greece',
  'GR',
  'Rethymno',
  'Mixorrouma (Agios Vasileios)',
  35.2211278,
  24.4979202,
  'https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Sheep and goat milk from Karines, cheesemaking since 1978',
  'Tzourmpakis is a family dairy in Mixorrouma, Rethymno, making traditional Cretan cheeses from sheep and goat milk. The dairy points specifically to herds grazing around Karines, linking its products to the pastoral landscape south of Rethymno.',
  'The family dates its cheesemaking activity to 1978. Its own account emphasises continuity rather than reinvention: milk from local grazing flocks, recipes and handling passed between generations, and modern food-safety certification supporting a traditional range of Cretan cheeses.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Contact dairy before visiting',
  NULL,
  '+30 28320 20013',
  'https://tzourmpakis.gr',
  'https://www.google.com/maps/place/%CE%A4%CF%85%CF%81%CE%BF%CE%BA%CE%BF%CE%BC%CE%B5%CE%AF%CE%BF+%CE%A4%CE%B6%CE%BF%CF%85%CF%81%CE%BC%CF%80%CE%AC%CE%BA%CE%B7/@35.2210821,24.4977471,21z/data=!4m14!1m7!3m6!1s0x149b6d60e5af177f:0x28f04e6827f00777!2zzqTPhc-Bzr_Ous6_zrzOtc6vzr8gzqTOts6_z4XPgc68z4DOrM66zrc!8m2!3d35.2211278!4d24.4979202!16s%2Fg%2F11bxd77_pt!3m5!1s0x149b6d60e5af177f:0x28f04e6827f00777!8m2!3d35.2211278!4d24.4979202!16s%2Fg%2F11bxd77_pt?entry=ttu&g_ep=EgoyMDI2MDkwOS4wIKXMDSoASAFQAw%3D%3D',
  NULL,
  'not_publicly_confirmed',
  'https://tzourmpakis.gr/',
  'Official Tzourmpakis information confirms the Mixorrouma dairy location and provides a map link. No explicit public road-surface, width, or vehicle-suitability classification is published, so road type remains unconfirmed.',
  'verified_location',
  'https://www.google.com/maps/place/%CE%A4%CF%85%CF%81%CE%BF%CE%BA%CE%BF%CE%BC%CE%B5%CE%AF%CE%BF+%CE%A4%CE%B6%CE%BF%CF%85%CF%81%CE%BC%CF%80%CE%AC%CE%BA%CE%B7/@35.2210821,24.4977471,21z/data=!4m14!1m7!3m6!1s0x149b6d60e5af177f:0x28f04e6827f00777!2zzqTPhc-Bzr_Ous6_zrzOtc6vzr8gzqTOts6_z4XPgc68z4DOrM66zrc!8m2!3d35.2211278!4d24.4979202!16s%2Fg%2F11bxd77_pt!3m5!1s0x149b6d60e5af177f:0x28f04e6827f00777!8m2!3d35.2211278!4d24.4979202!16s%2Fg%2F11bxd77_pt?entry=ttu&g_ep=EgoyMDI2MDkwOS4wIKXMDSoASAFQAw%3D%3D',
  'Current Tzourmpakis Dairy location supplied from the Google Maps business listing. Treat as verified location; entrance-level precision has not been separately established.',
  'current_access_uncertain',
  'https://tzourmpakis.gr/',
  'The current dairy and producer-controlled map destination are verified. Historical sources mention a shop on the Rethymno-Spili road, but current public walk-in instructions are not explicit enough to promise access.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'toplou-monastery-winery',
  'Ktima Toplou',
  'Κτήμα Τοπλού',
  'winery',
  'crete',
  'Greece',
  'GR',
  'Lasithi',
  'Sitia',
  35.2215,
  26.2163,
  'https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'Monastic vineyards and centuries of wine history in eastern Crete',
  'Ktima Toplou produces organic wines and spirits from the agricultural estate of the Holy Monastery of Toplou near Sitia. Vineyards, olive groves, dry soils and strong coastal winds connect the modern winery to a much older monastic farming landscape.',
  'Wine has long been part of monastery life here: an inscription on Toplou''s wine press records Liatiko cultivation in 1709. The monastery revived old vineyards and planted new ones in the late 1990s, leading to the modern winery and distillery that now carry this agricultural heritage forward.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Toplou Fabrica daily 10:00-18:00; winery contact Mon-Fri 08:30-16:30',
  NULL,
  '+30 28430 29630',
  'https://www.ktimatoplou.gr/',
  'https://maps.google.com/?q=35.2215,26.2163',
  NULL,
  'not_publicly_confirmed',
  'https://www.ktimatoplou.gr/',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://www.ktimatoplou.gr/en/contact-us-285',
  'Monastery/estate location is verified. Do not present the production winery pin as the tasting-room entrance; current tastings are at Toplou Fabrica in the monastery courtyard.',
  'public_visits',
  'https://www.ktimatoplou.gr/en/toplou-fabrica-tasting-room-315',
  'Public tastings are offered at Toplou Fabrica inside the courtyard of the Holy Monastery of Toplou. Ktima Toplou explicitly states that tastings do not take place at the production winery. The current monastery/estate location is suitable for reaching the visitor destination; use Toplou Fabrica instructions for final access.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'cretan-olive-oil-farm',
  'Spiridi Olive Oil Farm',
  'Spiridi Olive Oil Farm',
  'olive_mill',
  'crete',
  'Greece',
  'GR',
  'Lasithi',
  'Agios Nikolaos - Elounda Road',
  35.211141,
  25.7116105,
  'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80']::TEXT[],
  'A family farm where old olive-press history became a living museum',
  'Spiridi Olive Oil Farm, formerly Cretan Olive Oil Farm, combines family olive-oil production with a collection of traditional Cretan food and craft practices on the Agios Nikolaos–Elounda road. At its centre is a restored nineteenth-century olive press brought from the village of Vrouha.',
  'The project grew unexpectedly from work on books about the Cretan diet in the 1990s, which led the family to reconnect with older recipes, ingredients and producers across the island. After years of welcoming visitors, they rebuilt their family''s 1882 olive press inside the museum; in 2024 the farm took the Spiridi name to foreground the family legacy.',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Mon-Sat 09:30-19:00; Sun 10:00-16:00',
  NULL,
  '+30 28410 24139',
  'https://cretanoliveoilfarm.com',
  'https://maps.google.com/?q=35.211141,25.711611',
  NULL,
  'not_publicly_confirmed',
  'https://cretanoliveoilfarm.com',
  'Phase 6 review (2026-09-13): no explicit source-backed road-surface, width, or vehicle-suitability classification was found in the reviewed public material. Road type remains unpublished.',
  'verified_location',
  'https://cretanoliveoilfarm.com',
  'Current Spiridi Olive Oil Farm identity and Agios Nikolaos-Elounda road location verified. Producer advises checking current timetable.',
  'public_visits',
  'https://www.cretanoliveoilfarm.com/',
  'Spiridi explicitly operates as a visitor farm and museum and publishes daily opening hours and self-guided access.',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  greek_name = EXCLUDED.greek_name,
  category = EXCLUDED.category,
  destination = EXCLUDED.destination,
  country = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  region = EXCLUDED.region,
  village = EXCLUDED.village,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  cover_image = EXCLUDED.cover_image,
  gallery = EXCLUDED.gallery,
  tag_line = EXCLUDED.tag_line,
  description = EXCLUDED.description,
  story = EXCLUDED.story,
  indigenous_varieties = EXCLUDED.indigenous_varieties,
  tasting_highlights = EXCLUDED.tasting_highlights,
  opening_hours = EXCLUDED.opening_hours,
  best_season = EXCLUDED.best_season,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  google_maps_url = EXCLUDED.google_maps_url,
  road_access = EXCLUDED.road_access,
  road_access_status = EXCLUDED.road_access_status,
  road_access_source_url = EXCLUDED.road_access_source_url,
  road_access_notes = EXCLUDED.road_access_notes,
  location_status = EXCLUDED.location_status,
  location_source_url = EXCLUDED.location_source_url,
  location_notes = EXCLUDED.location_notes,
  visit_status = EXCLUDED.visit_status,
  visit_source_url = EXCLUDED.visit_source_url,
  visit_notes = EXCLUDED.visit_notes,
  ethos = EXCLUDED.ethos,
  food_option = EXCLUDED.food_option,
  dog_friendly = EXCLUDED.dog_friendly,
  kid_friendly = EXCLUDED.kid_friendly,
  walk_in_friendly = EXCLUDED.walk_in_friendly,
  campervan_friendly = EXCLUDED.campervan_friendly,
  price_level = EXCLUDED.price_level,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  vip_perks = EXCLUDED.vip_perks,
  updated_at = NOW();
