-- Phase 13 dairy Google identity follow-up.
--
-- Persist only independently audited persistent Google Place IDs. These updates
-- intentionally do not infer visitor access or road conditions from Google Maps.
-- The location geometry is generated by the producers table from lat/lng.

update public.producers
set
  google_place_id = 'ChIJIZTR0koHmxQRQqWZvFNSOGU',
  google_maps_url = 'https://www.google.com/maps/search/?api=1&query=35.3038706%2C24.8093411&query_place_id=ChIJIZTR0koHmxQRQqWZvFNSOGU',
  location_source_url = 'https://www.google.com/maps/search/?api=1&query=35.3038706%2C24.8093411&query_place_id=ChIJIZTR0koHmxQRQqWZvFNSOGU',
  updated_at = now()
where id = 'psiloritis-cheese-dairy-livadia'
  and location_status in ('verified_location', 'verified_entrance');

update public.producers
set
  lat = 37.5904969,
  lng = 22.7115766,
  google_place_id = 'ChIJA4BioIz8nxQRZCVKZG8kO3I',
  google_maps_url = 'https://www.google.com/maps/search/?api=1&query=ARGOGAL%20Kefalari%20Argos&query_place_id=ChIJA4BioIz8nxQRZCVKZG8kO3I',
  location_source_url = 'https://www.argogal.gr/en/contact',
  location_notes = 'Producer-controlled ARGOGAL contact page links directly to the Google Maps business point for Andrea Koromichi Sons / ARGOGAL in Kefalari, Argos. The linked Google feature resolves to the persistent Place ID ChIJA4BioIz8nxQRZCVKZG8kO3I at 37.5904969, 22.7115766. This verifies the production-business location, not a specific visitor entrance.',
  updated_at = now()
where id = 'argogal-koromichi-kefalari'
  and location_status in ('verified_location', 'verified_entrance');
